# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://deanbr.io
title: Brandon Dean
email: deanbr@vt.edu
author: Brandon Dean
description: > # todo
copyright: '2018 Brandon Dean'
credits: ''

# Google tracking id
google_tracking_id: "UA-102223117-1"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/deanbr/
    source: ../img/icons/github_transparent.png
  - title: linkedin
    url: https://www.linkedin.com/in/brandon-dean-4772a067/
    source: ../img/icons/linkedin_transparent.png
  - title: resume
    url: https://drive.google.com/uc?export=download&amp;id=1-NCY8Unj7s8JvJYlh_2LN_lNsY2FToSd
    source: ../img/icons/resume_transparent.png
