# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://deanbr.github.io/
baseurl: deanbr.io
title: Brandon Dean
author: Brandon Dean
description: Brandon Dean
avatar: profile.png
email: deanbr@vt.edu
github: deanbr
twitter: # username
linkedin: username
stackoverflow: #username   #e.g: users/2735833/proton1h1
google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
