# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://deanbr.io
title: Brandon Dean
email: deanbr@vt.edu
author: Brandon Dean
description: > # todo
copyright: 'Copyright &copy; 2017 Brandon Dean'
credits: ''

# Google tracking id
google-tracking-id: "UA-91627328-1"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/deanbr/
  - title: linkedin
    url: https://www.linkedin.com/in/brandon-dean-4772a067/
  - title: resume
    url: https://drive.google.com/uc?export=download&amp;id=0B9X7rJJ_usgQazNkUXFjV1FBUVE
